[phases.setup]
nixPkgs = ["nodejs_20", "git", "python3", "nodePackages.node-gyp"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = ["echo 'No build step'"]

[start]
cmd = "node src/server.js"
